# 4.8 Grouping Data & Aggregating Variables

## 01. Importing Libraries

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import os

## 02. Importing Data

In [3]:
# Import orders_products_merged data from Prepared Data folder
ords_prods_merge = pd.read_pickle(r'C:\Users\lrutl\OneDrive\Desktop\Python Fundamentals for Data Analysts\Instacart Basket Analysis\02 Data\Prepared Data\orders_products_merged_updated.pkl')

In [4]:
ords_prods_merge.head()

,order_id,customer_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,Busiest_days,Busiest days,busiest_period_of_day
0,2398795,1,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,2 slowest days,Average orders
1,473747,1,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,2 slowest days,Most orders
2,2254736,1,4,4,7,29.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Least busy,2 slowest days,Average orders
3,431534,1,5,4,15,28.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Least busy,2 slowest days,Most orders
4,3367565,1,6,2,7,19.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,regular,Average orders

In [5]:
ords_prods_merge.shape

(30328763, 19)

In [9]:
ords_prods_merge.head()

,order_id,customer_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,Busiest days,busiest_period_of_day
0,2398795,1,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Average orders
1,473747,1,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders
2,2254736,1,4,4,7,29.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Average orders
3,431534,1,5,4,15,28.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders
4,3367565,1,6,2,7,19.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Average orders

In [10]:
# Create subset of ords_prods_merge with first 1MM rows
df = ords_prods_merge[:1000000]

In [11]:
df.shape

(1000000, 18)

In [12]:
df.head(10)

,order_id,customer_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,Busiest days,busiest_period_of_day
0,2398795,1,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Average orders
1,473747,1,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders
2,2254736,1,4,4,7,29.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Average orders
3,431534,1,5,4,15,28.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders
4,3367565,1,6,2,7,19.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Average orders
5,550135,1,7,1,9,20.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders
6,3108588,1,8,1,14,14.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders
7,2295261,1,9,1,16,0.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders
8,2550362,1,10,4,8,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Average orders
9,2968173,15,15,1,9,7.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders

## 03. Grouping Data with Pandas

In [13]:
# Group by product name
df.groupby('product_name')

## 04. Aggregating Data with agg()

In [14]:
# Split the data into groups based on "department_id". 
# Apply the agg() function to each group to obtain the mean values for the "order_number" column.
df.groupby('department_id').agg({'order_number' : ['mean']})

              order_number
                      mean
department_id
4                19.765396
7                18.575283
13               18.950838
14               20.460336
16               20.262396
17               12.646785
19               20.168036
20               18.808671

In [15]:
# Get order_number mean, min and max by department_id
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                19.765396   2  99
7                18.575283   2  99
13               18.950838   2  99
14               20.460336   2  99
16               20.262396   2  99
17               12.646785   2  98
19               20.168036   2  99
20               18.808671   2  99

## 05. Aggregating Data with transform()

In [29]:
# 1. Split data into groups based on "user_id" column.
# 2. Apply the transform() function on the “order_number” column to generate the maximum orders for each user.
# 3. Create a new column, “max_order,” into which you’ll place the results of your aggregation.
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['customer_id'])['order_number'].transform(np.max)

In [30]:
ords_prods_merge.head(15)

,order_id,customer_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,Busiest days,busiest_period_of_day,max_order
0,2398795,1,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Average orders,10
1,473747,1,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders,10
2,2254736,1,4,4,7,29.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Average orders,10
3,431534,1,5,4,15,28.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders,10
4,3367565,1,6,2,7,19.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Average orders,10
5,550135,1,7,1,9,20.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,10
6,3108588,1,8,1,14,14.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,10
7,2295261,1,9,1,16,0.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,10
8,2550362,1,10,4,8,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Average orders,10
9,2968173,15,15,1,9,7.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,22
10,1870022,15,17,2,16,8.0,196,6,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,22
11,1911383,15,18,2,11,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,22
12,2715276,15,21,1,9,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,22
13,487368,15,22,1,10,14.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,22
14,2293453,19,2,5,14,6.0,196,3,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,9

In [31]:
# Remove Pandas limit to display rows
pd.options.display.max_rows = None

In [32]:
ords_prods_merge.head(100)

,order_id,customer_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,Busiest days,busiest_period_of_day,max_order
0,2398795,1,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Average orders,10
1,473747,1,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders,10
2,2254736,1,4,4,7,29.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Average orders,10
3,431534,1,5,4,15,28.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders,10
4,3367565,1,6,2,7,19.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Average orders,10
5,550135,1,7,1,9,20.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,10
6,3108588,1,8,1,14,14.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,10
7,2295261,1,9,1,16,0.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,10
8,2550362,1,10,4,8,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Average orders,10
9,2968173,15,15,1,9,7.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,22
10,1870022,15,17,2,16,8.0,196,6,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,22
11,1911383,15,18,2,11,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,22
12,2715276,15,21,1,9,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,22
13,487368,15,22,1,10,14.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,22
14,2293453,19,2,5,14,6.0,196,3,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,9
15,1973799,19,5,6,12,8.0,196,15,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,9
16,532817,19,7,4,17,6.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Average orders,9
17,1573906,21,10,3,10,6.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders,33
18,1593000,31,10,3,8,7.0,196,17,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Average orders,20
19,2231262,31,17,3,11,8.0,196,14,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders,20
20,2580647,43,6,4,16,4.0,196,9,0,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders,11
21,2187180,43,9,4,12,3.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders,11
22,1318871,52,2,1,10,7.0,196,5,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,27
23,1261384,52,3,1,10,7.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,27
24,580568,52,5,2,10,8.0,196,6,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,27
25,2428073,52,7,2,7,8.0,196,5,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Average orders,27
26,342306,52,9,1,11,7.0,196,5,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,27
27,1520353,52,10,2,10,8.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,27
28,2542086,52,11,2,9,7.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,27
29,944694,52,12,1,16,6.0,196,7,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,27
30,1268191,52,15,2,11,8.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,27
31,1122089,52,17,2,10,6.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,27
32,1498922,52,18,2,10,14.0,196,6,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,27
33,180919,52,19,3,8,8.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Average orders,27
34,2695875,52,21,5,10,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,27
35,970922,67,2,1,15,5.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,24
36,596585,67,3,1,13,7.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,24
37,2037087,67,4,2,9,8.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,24
38,2474111,67,5,3,14,8.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders,24
39,1568481,67,6,3,12,7.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders,24
40,2048527,67,8,2,11,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,24
41,2389031,67,9,2,14,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,24
42,2378562,67,10,1,10,6.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,24
43,1515698,67,11,1,11,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,24
44,1928050,67,12,2,12,8.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,24
45,1949274,67,13,1,10,6.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,24
46,551869,67,14,1,9,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,24
47,768572,67,16,4,10,9.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders,24
48,150528,67,18,5,16,4.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,24
49,29758,67,19,0,14,9.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Busiest day,2 busiest days,Most orders,24
50,1558976,67,21,1,9,5.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,24
51,863974,67,22,1,11,14.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,24
52,2308399,67,23,1,14,14.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,24
53,2759128,81,3,1,9,14.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,7
54,1812985,81,5,2,20,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Average orders,7
55,499460,82,3,5,10,5.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,19
56,2728456,82,4,0,11,16.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Busiest day,2 busiest days,Most orders,19
57,2653743,82,6,4,9,13.0,196,5,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders,19
58,1358880,82,9,1,10,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,19
59,343588,82,10,2,11,1.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,19
60,3034663,82,15,2,11,12.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,19
61,147262,82,18,1,13,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,19
62,3144004,82,19,2,15,8.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,19
63,2126069,98,3,0,9,25.0,196,7,0,both,Soda,77,7,9.0,Mid-range product,Busiest day,2 busiest days,Most orders,14
64,2210120,98,7,5,14,5.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,14
65,681011,98,9,3,9,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders,14
66,2846344,98,11,4,13,15.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders,14
67,747431,98,12,6,13,30.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,14
68,2383054,98,13,4,11,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders,14
69,1993729,98,14,5,8,8.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Average orders,14
70,1403849,109,3,3,17,9.0,196,5,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Average orders,6
71,3273029,120,3,2,8,19.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Average orders,3
72,1861943,185,2,1,12,25.0,196,10,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,6
73,1680569,195,8,1,9,4.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,58
74,276171,195,19,5,11,3.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,58
75,2744976,195,22,5,10,7.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,58
76,2781919,195,25,1,14,4.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,58
77,1738718,195,31,2,8,4.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Average orders,58
78,3058369,195,34,3,10,6.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders,58
79,1485596,195,37,2,15,0.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,58
80,417035,195,40,3,16,2.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders,58
81,1615297,195,47,5,10,2.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,58
82,1765587,195,52,3,12,2.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Most orders,58
83,745908,195,57,4,11,3.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders,58
84,2505656,222,17,2,12,1.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,70
85,3268370,222,38,5,15,1.0,196,6,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,70
86,2016711,290,9,5,19,6.0,196,8,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Average orders,51
87,2706088,290,28,6,10,7.0,196,16,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,51
88,1952286,331,6,5,16,30.0,196,8,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,8
89,1469869,377,3,5,17,3.0,196,9,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Average orders,3
90,1927023,387,2,4,10,22.0,196,3,0,both,Soda,77,7,9.0,Mid-range product,Least busy,2 slowest days,Most orders,8
91,858092,420,4,1,19,30.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Average orders,22
92,119314,420,5,3,19,16.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Average orders,22
93,1665683,423,3,2,11,7.0,196,3,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,42
94,3096825,423,19,2,11,7.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,42
95,1548901,546,4,3,18,23.0,196,1,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 slowest days,Average orders,6
96,668870,591,2,1,13,7.0,196,1,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,7
97,2483801,626,2,5,15,2.0,196,10,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,regular,Most orders,94
98,2741904,626,6,1,14,5.0,196,12,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,94
99,2138689,626,10,1,10,4.0,196,5,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,2 busiest days,Most orders,94

## 06. Deriving Columns with loc()

In [35]:
# Create flag to assign a "loyalty" label to a user ID based on corresponding max order value.
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [36]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [37]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [38]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15081691
Loyal customer      10095381
New customer         5151691
Name: loyalty_flag, dtype: int64

In [42]:
ords_prods_merge[['customer_id', 'loyalty_flag', 'order_number']].head(60)

    customer_id      loyalty_flag  order_number
0             1      New customer             2
1             1      New customer             3
2             1      New customer             4
3             1      New customer             5
4             1      New customer             6
5             1      New customer             7
6             1      New customer             8
7             1      New customer             9
8             1      New customer            10
9            15  Regular customer            15
10           15  Regular customer            17
11           15  Regular customer            18
12           15  Regular customer            21
13           15  Regular customer            22
14           19      New customer             2
15           19      New customer             5
16           19      New customer             7
17           21  Regular customer            10
18           31  Regular customer            10
19           31  Regular customer            17
20           43  Regular customer             6
21           43  Regular customer             9
22           52  Regular customer             2
23           52  Regular customer             3
24           52  Regular customer             5
25           52  Regular customer             7
26           52  Regular customer             9
27           52  Regular customer            10
28           52  Regular customer            11
29           52  Regular customer            12
30           52  Regular customer            15
31           52  Regular customer            17
32           52  Regular customer            18
33           52  Regular customer            19
34           52  Regular customer            21
35           67  Regular customer             2
36           67  Regular customer             3
37           67  Regular customer             4
38           67  Regular customer             5
39           67  Regular customer             6
40           67  Regular customer             8
41           67  Regular customer             9
42           67  Regular customer            10
43           67  Regular customer            11
44           67  Regular customer            12
45           67  Regular customer            13
46           67  Regular customer            14
47           67  Regular customer            16
48           67  Regular customer            18
49           67  Regular customer            19
50           67  Regular customer            21
51           67  Regular customer            22
52           67  Regular customer            23
53           81      New customer             3
54           81      New customer             5
55           82  Regular customer             3
56           82  Regular customer             4
57           82  Regular customer             6
58           82  Regular customer             9
59           82  Regular customer            10

## 07. Export df in pickle format

In [43]:
ords_prods_merge.to_pickle(os.path.join(r'C:\Users\lrutl\OneDrive\Desktop\Python Fundamentals for Data Analysts\Instacart Basket Analysis\02 Data\Prepared Data\orders_products_merged_updated_v2.pkl'))